In [1]:
import torch
import numpy as np
from collections import OrderedDict

In [2]:
!ls

float16_model.pth  irse50_convert_float32_to_float16.ipynb  model_ir_se50.pth


In [3]:
#load the model

model = torch.load('model_ir_se50.pth')

## Weight's visualiztions

In [9]:
for layer_name, weights in model.items():
    print(layer_name)
    print(model[layer_name][model[layer_name] <= 0])

input_layer.0.weight
tensor([-7.7629e-03, -2.9490e-02, -1.5910e-02, -3.1693e-02, -1.3233e-02,
        -7.2145e-03, -7.6193e-02, -1.3327e-01, -1.0719e-01, -1.3083e-01,
        -1.7606e-01, -1.9564e-01, -1.9856e-02, -5.7511e-02, -5.4179e-02,
        -1.5232e-02, -7.3336e-03, -9.8282e-02, -3.8003e-02, -1.0607e-01,
        -1.6987e-01, -8.2032e-02, -1.7212e-01, -8.8697e-02, -6.9822e-02,
        -5.2662e-02, -1.8383e-02, -7.4249e-03, -9.0790e-02, -1.3567e-01,
        -5.1803e-02, -8.9306e-02, -6.2175e-02, -7.0664e-02, -6.8413e-02,
        -6.3342e-02, -2.6187e-02, -3.8295e-02, -9.3375e-02, -9.3960e-03,
        -6.8579e-02, -3.3897e-03, -5.9789e-02, -2.0342e-02, -3.4965e-02,
        -4.6514e-02, -4.0836e-02, -1.3739e-02, -4.8817e-02, -5.2546e-02,
        -1.5892e-03, -1.0483e-02, -3.4481e-02, -3.1378e-02, -2.6821e-03,
        -4.4180e-02, -2.4737e-02, -2.3964e-02, -2.9042e-02, -1.8547e-02,
        -4.6684e-02, -2.0979e-03, -3.3278e-02, -4.7134e-02, -2.6307e-02,
        -6.1156e-02, -9.2763e-

tensor([-0.0069, -0.0765, -0.0132, -0.0087, -0.0105, -0.1584, -0.0992, -0.0051,
        -0.0079, -0.0075, -0.0262, -0.1010, -0.0110, -0.0239, -0.0339, -0.0063,
        -0.0097, -0.0520, -0.0064, -0.0200, -0.0014, -0.0469, -0.0184, -0.0290,
        -0.0102, -0.0430, -0.0213, -0.2114, -0.1728, -0.0073, -0.0241, -0.0296,
        -0.0400, -0.0005, -0.0494, -0.0123, -0.0144, -0.0379, -0.0064, -0.0245,
        -0.0079, -0.0474, -0.0197, -0.0341, -0.0079, -0.0088, -0.0087, -0.0180,
        -0.0309, -0.0389, -0.0546, -0.0144, -0.0131, -0.0041, -0.0369, -0.0125,
        -0.0380, -0.0069, -0.0146, -0.0360, -0.0065, -0.0058, -0.0083, -0.0215,
        -0.0085, -0.0044, -0.0207, -0.0123, -0.0181, -0.0135, -0.0037, -0.0250,
        -0.0362, -0.0384, -0.0052, -0.0156, -0.0625, -0.0568, -0.0066, -0.0074,
        -0.0114, -0.0074, -0.0110, -0.0156, -0.0078, -0.0090, -0.0050, -0.0324,
        -0.0159, -0.0152, -0.0176, -0.0202, -0.0304, -0.0088, -0.0314, -0.0024],
       device='cuda:0')
body.0.res_laye

tensor([-1.4515e-03, -1.2724e-03, -2.7316e-03, -1.5005e-03, -1.9616e-05,
        -3.4645e-04, -6.0801e-04, -1.1670e-02, -5.1026e-04, -2.6783e-03,
        -3.0203e-03, -8.4521e-04, -2.7211e-03, -2.1894e-03, -4.3617e-03,
        -1.0670e-03, -9.6365e-04, -1.8231e-03, -4.9255e-03, -2.7296e-03,
        -1.3870e-03, -2.2265e-03, -1.1493e-04, -4.0248e-04, -1.5128e-03,
        -2.7688e-04, -3.4317e-03, -5.6081e-04, -3.2034e-04, -1.5154e-03,
        -3.8986e-03, -3.0691e-03, -8.7495e-03, -2.6382e-03, -5.0532e-03,
        -1.5381e-03, -4.2228e-03, -5.3593e-04, -1.1800e-03, -1.4074e-03,
        -2.7441e-03, -1.1535e-04, -3.7954e-04, -1.2144e-02, -4.6057e-04,
        -6.1689e-03, -2.1758e-03, -4.0052e-03, -7.1031e-04, -1.1029e-03,
        -9.5190e-04, -3.7658e-03, -3.1795e-03, -1.3282e-02, -1.0694e-02,
        -1.0729e-03, -1.7420e-03, -1.9752e-03, -1.7906e-03, -2.6839e-03,
        -4.3123e-03, -3.7843e-03, -6.2385e-04, -9.5964e-04, -2.5153e-03,
        -2.3979e-03, -8.4271e-04, -1.7299e-03, -2.1

tensor([-0.0017, -0.0044, -0.0034,  ..., -0.0365, -0.0310, -0.0203],
       device='cuda:0')
body.17.res_layer.4.weight
tensor([-0.0042, -0.0180, -0.0002, -0.0173], device='cuda:0')
body.17.res_layer.4.bias
tensor([-5.7424e-04, -1.9380e-04, -4.5613e-04, -4.6491e-04, -1.0968e-03,
        -9.8922e-04, -8.9747e-04, -1.8547e-04, -3.6751e-04, -7.9778e-05,
        -7.5980e-04, -5.1135e-04, -6.1744e-05, -3.1661e-04, -1.5333e-04,
        -5.2126e-04, -1.5811e-05, -1.5012e-04, -5.9372e-04, -3.5387e-04,
        -5.5615e-04, -6.0232e-04, -1.0731e-03, -5.1909e-04, -2.4444e-04,
        -1.0149e-04, -1.4708e-04, -2.9546e-05, -5.8187e-04, -5.2253e-05,
        -9.1078e-04, -2.6626e-04, -2.0589e-04, -7.0504e-05, -4.0076e-04,
        -8.0957e-04, -9.0832e-04, -1.8683e-04, -1.5579e-04, -9.6386e-04,
        -2.4141e-04, -7.9070e-04, -7.1374e-04, -6.0776e-04, -7.9645e-04,
        -3.7008e-04, -1.0472e-03, -1.7070e-04, -3.3513e-04, -4.9362e-04,
        -5.8763e-04, -6.2325e-04, -5.0145e-04, -2.3378e-04, -7.

tensor([-0.0763, -0.0900, -0.1210, -0.0623, -0.0901, -0.1117, -0.0615, -0.0836,
        -0.0279, -0.1469, -0.1132, -0.1211, -0.0304, -0.1018, -0.0838, -0.1307,
        -0.1364, -0.1008, -0.0831, -0.0665, -0.0123, -0.1255, -0.0817, -0.0053,
        -0.1282, -0.1183, -0.0989, -0.0307, -0.0729, -0.0276, -0.0907, -0.1220,
        -0.0114, -0.0588, -0.0057, -0.0961, -0.1455, -0.0879, -0.1099, -0.0653,
        -0.0030, -0.0064, -0.0913, -0.0864, -0.0799, -0.0025, -0.0424, -0.0263,
        -0.0250, -0.1210, -0.1300, -0.1412, -0.1105, -0.0332, -0.1378, -0.1479,
        -0.1008, -0.0096, -0.0341, -0.0894, -0.0536, -0.0737, -0.1032, -0.1013,
        -0.0898, -0.0738, -0.0917, -0.0023, -0.1083, -0.0504, -0.0095, -0.1042,
        -0.0214, -0.0398, -0.0622, -0.0395, -0.0888, -0.0989, -0.0560, -0.0742,
        -0.0728, -0.0424, -0.0994, -0.1024, -0.0473, -0.0990, -0.0277, -0.0344,
        -0.0473, -0.0232, -0.0949, -0.0936, -0.1475, -0.0644, -0.1085, -0.1095,
        -0.1358, -0.1151, -0.1381, -0.08

In [10]:
input_layer_w0 = model['input_layer.0.weight'][model['input_layer.0.weight'] == 0]
test = input_layer_w0[input_layer_w0 == 0]
input_layer_w0

tensor([], device='cuda:0')

## Convert all the weights Float32 to Float16

In [76]:
# Converts float32 datatype to float16 
# per layer weights of given model

def convert_to_float16(weights):
    converted = model[weights].to(dtype = torch.float16)
    print(converted.dtype)
    return converted

In [77]:
# initialize a ordered dictionary

float16_model = OrderedDict()

In [78]:
for layer_name, weights in model.items():
    float16_model[layer_name] = convert_to_float16(layer_name)
#     print(layer_name)

torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.float16
torch.

In [80]:
torch.save(float16_model, './float16_model.pth')

```
After converting to float16 save the model. You'll see new model is around 50-60% smaller than 
the old model.
In my case, its 175.4MB to 87.7MB
```